/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var d=Object.defineProperty;var p=Object.getOwnPropertyDescriptor;var m=Object.getOwnPropertyNames;var u=Object.prototype.hasOwnProperty;var h=(n,t)=>{for(var r in t)d(n,r,{get:t[r],enumerable:!0})},y=(n,t,r,i)=>{if(t&&typeof t=="object"||typeof t=="function")for(let e of m(t))!u.call(n,e)&&e!==r&&d(n,e,{get:()=>t[e],enumerable:!(i=p(t,e))||i.enumerable});return n};var f=n=>y(d({},"__esModule",{value:!0}),n);var g={};h(g,{default:()=>a});module.exports=f(g);var l=require("obsidian"),a=class extends l.Plugin{async onload(){this.registerEvent(this.app.workspace.on("editor-paste",this.handlePaste.bind(this)))}handlePaste(t,r,i){var s;let e=(s=t.clipboardData)==null?void 0:s.getData("text/plain");if(!e||!e.includes("<details")||!e.includes("<summary>"))return;let o=this.convertDetailsToCallout(e);o!==e&&(t.preventDefault(),r.replaceSelection(o))}convertDetailsToCallout(t){return t.replace(/<details(?:\s+open)?>\s*<summary>(.*?)<\/summary>([\s\S]*?)<\/details>/gi,(r,i,e)=>{let s=e.trim().split(`
`).map(c=>`> ${c}`).join(`
`);return`> [!NOTE]+ ${i}
${s}`})}};
